#transparency
#backened specified
backend = "glx";
#glx-no-stencil = true; #discontinued in newer versions
glx-copy-from-front = false;
use-damage=true;
vsync=true;
#opacity
active-opacity = 1;
inactive-opacity = 1;
frame-opacity = 1;
inactive-opacity-override = false;
blur-background = true;
blur-background-exclude = [
];

blur-method = "dual_kawase";
blur-strength = 2;

#Fading
fading = true;
fade-delta = 7;
no-fading-openclose = false;

fade-exclude = [];

opacity-rule =[
	"100:class_g = 'Alacritty' && focused ",
	"80:class_g = 'Alacritty' && !focused",
];

corner-radius = 10;

shadow = true;
shadow-ignore-shaped = false;
